### ISSUE TITLE
Navigation/Hamburger Menu - Mobile & Desktop

### ISSUE THREAD

**Issue by jkc96** [SeleneChoi/QA#3]
**Description:**

When entering the url [www.qa-test.julie-chan.ca](https://qa-test.julie-chan.ca/) there are visual and functional discrepancies on mobile and desktop screens

> a) We can see the hamburger menu is displayed when the navigation is expanded. This is on the home, our speakers, and our team page.
> b) we cannot see the logo or the hamburger menu on mobile screens. This prevents the end user from being able to navigate the website. 

Originally the navigation hamburger menu has the logo and hamburger menu on the top. The company logo on the top left side while the hamburger menu is made up of 3 white lines located on the top right side.

**Steps to Reproduce:**

Open on desktop using browsers Safari, Chrome, Firefox, or Edge.

Visit [www.qa-test.julie-chan.ca](https://qa-test.julie-chan.ca/)
When entering the website, the, you will visit the Front/Home page
1) The hamburger menu appears in the navigation menu, above the “Join Event” button
Click on the Our Speakers page
2) The hamburger menu appears in the navigation menu, above the “Join Event” button
Click on the Our Team page
3) The hamburger menu appears in the navigation menu, above the “Join Event” button

Open on mobile using browsers Safari, Chrome, Firefox, or Edge.

4)	Visit [www.qa-test.julie-chan.ca](https://qa-test.julie-chan.ca/)
5)	When entering the website, you will visit the Front/Home page
> a)	The navigation menu has no logo or hamburger menu at all
> b)	Because the Front/Home page does not consist of the menu, there is no method to navigate the website unless manually typing the URL for other pages

**Expected Result:**
When the screen is loaded on a desktop, we expect the hamburger menu to be hidden when navigating the website on desktop screen on all browsers.

- When the page loads, the navigation is expanded.
- On the top from left to right, the navigation should have the logo, a gap, then a “Join Event” button, Home, Event Details, Our Speakers, and Our Team.
- When clicking on any page of the website, the navigation menu is to remain the same with no visual changes.

When the screen is loaded on a mobile, we expect the logo and hamburger menu to be displayed on the top when navigating the website on desktop screen on all browsers. 
 
- When the page loads, the navigation is expanded.
- On the top from left to right, the navigation should have the logo, a gap, then a “Join Event” button, Home, Event Details, Our Speakers, and Our Team.
- When clicking on any page of the website, the navigation menu is to remain the same with no visual changes.

**Actual Result:**

Refer to the attached documents for screenshot of bug.

**Mac - Safari **
![bug1-mac-safari](https://github.com/SeleneChoi/QA/assets/115045111/c8498711-b29d-4ad0-b581-2db0131893e6)

**Mac - Chrome **
![bug1-mac-chrome](https://github.com/SeleneChoi/QA/assets/115045111/1a162f8c-5d08-4bae-8a49-e05301185deb)

**Mac - Firefox **
![bug1-mac-firefox](https://github.com/SeleneChoi/QA/assets/115045111/71bb690c-0400-40c6-bb57-9c1c7f636736)

**Mac - Edge **
![bug1-mac-edge](https://github.com/SeleneChoi/QA/assets/115045111/c0ea63f5-cc36-4f76-8b0e-574bcf65788b)

**Windows - Chrome**
![bug1-windows-chrome](https://github.com/SeleneChoi/QA/assets/115045111/5194dc7d-0d50-4bd8-a2a9-3ab9800bdb52)

**Windows - Edge**
![bug1-windows-edge](https://github.com/SeleneChoi/QA/assets/115045111/50465a3e-8fe9-4bd3-9a27-2c6dd67fe321)

**Windows - Firefox**
![bug1-windows-firefox](https://github.com/SeleneChoi/QA/assets/115045111/7b71eef0-62a7-4eef-8064-0abd06905408)

**iPhone – Safari**
![but2-iphone-safari](https://github.com/SeleneChoi/QA/assets/115045111/fdbb0c56-f9e8-44fa-a889-f332ec11103d)

**iPhone – Chrome**
![bug2-iphone-chrome](https://github.com/SeleneChoi/QA/assets/115045111/2630d284-f3a3-4872-a88e-0d082c066ddb)

**iPhone – Edge**
![but2-iphone-edge](https://github.com/SeleneChoi/QA/assets/115045111/25ebe316-0bf9-4878-85fe-40da57070adb)

**iPhone – Firefox**
![but2-iphone-firefox](https://github.com/SeleneChoi/QA/assets/115045111/d21874f3-9f1f-4562-a90c-e6e9ed2a48e1)

**Samsung – Chrome**
<img width="352" alt="bug2-samsung-chrome" src="https://github.com/SeleneChoi/QA/assets/115045111/337509d6-c4d2-437e-940d-bd700d79c87e">

**Samsung – Firefox**
<img width="352" alt="bug2-samsung-firefox" src="https://github.com/SeleneChoi/QA/assets/115045111/b0cbb56a-5614-4341-96ec-e8a667ca9ed9">

**Samsung - Edge**
<img width="352" alt="bug2-samsung-edge" src="https://github.com/SeleneChoi/QA/assets/115045111/b7439103-7497-450c-b76d-082dc6c69728">

**Comment by Jpduque25** [comment]
Created a hamburger menu with the use of html and css while also implementing changes in flex items so that the join event button would be located at the bottom of the mobile menu for users to see. 

Hamburger menu button is displayed as hidden only on desktop screens and only when the user is viewing the site through tablet and mobile screens will they be able to access the hamburger menu button. 

Imported our company logo.

**Comment by Jpduque25** [comment]
Created a hamburger menu with the use of html and css while also implementing changes in flex items so that the join event button would be located at the bottom of the mobile menu for users to see.

Hamburger menu button is displayed as hidden only on desktop screens and only when the user is viewing the site through tablet and mobile screens will they be able to access the hamburger menu button.

Imported our company logo.
