### ISSUE TITLE
Scroll-to Button Non-functional – Mobile & Desktop

### ISSUE THREAD

**Issue by jkc96** [SeleneChoi/QA#4]
**Description:**

After entering the url [www.qa-test.julie-chan.ca](https://qa-test.julie-chan.ca/), the scroll-to buttons that fail to scroll to the bottom footer where users can register for the event. 

There are two buttons that can be found on the website:
•	The first button is on the Front/Home page, on the left-bottom column of the hero section
•	The second button is on the header and can be accessed on any page of the website
•	Both buttons are styled to have an orange container with white font color.

**Steps to Reproduce:**

_**This bug is found on all devices and browsers:**_

1.	Visit [www.qa-test.julie-chan.ca](https://qa-test.julie-chan.ca/)
2.	On the Front/Home Page:
a.	Click the “Join Event” button located on the hero section. The button is located on the bottom left side.
b.	When clicking the button, there is no action or change in screen.
3.	On all pages
a.	The navigation menu contains a “Join Event” button in between the logo and Home menu.
b.	Because the Front/Home page does not consist of the menu, there is no method When clicking the button, there is no action or change in screen.

**Expected Result:**

We expect both “Join Event” buttons will scroll down to the footer section for users to register for the event. 
 
•	When the page loads, the scroll-to buttons are located in the header and front/home page hero section.
•	When clicking on either buttons, the page should automatically scroll to the very bottom of the screen.

**Actual Result:**

Refer to the attached documents for screenshot of bug.

Button 1: Front/Home >> Hero Section
<img width="1417" alt="bug3-hero-section" src="https://github.com/SeleneChoi/QA/assets/115045111/c99d32c0-d1b4-4c93-8f4f-8a0d185f1078">

Button 2: All Pages >> Header
<img width="639" alt="bug3-header" src="https://github.com/SeleneChoi/QA/assets/115045111/39dedde9-b1be-4f68-9dd4-a940f1c9a9f0">

**Comment by SeleneChoi** [comment]
1. Id for the registration form part added : #registration
2. a tag added for corresponding buttons ( header.php and one extra button on index.php )

The link works successfully. The issue has been solved.
