### ISSUE TITLE
Registeration Error – Mobile & Desktop

### ISSUE THREAD

**Issue by jkc96** [SeleneChoi/QA#5]
**Description:**

When users enter url [www.qa-test.julie-chan.ca](https://qa-test.julie-chan.ca/) to register for the event, a message appears stating a connection error. When users submit their email or email and LinkedIn URL, the information fails to go to the backend server and no data is stored.

**Steps to Reproduce:**

This bug is found on all devices and browsers:

1.	Visit [www.qa-test.julie-chan.ca](https://qa-test.julie-chan.ca/)
2.	On the footer of all pages there is a “Join Event” section
a.	Type in any email with the option to add a LinkedIn URL
3.	Click “Register” button to submit the information
4.	The screen will reload back to the top of the back, scroll down to the footer section
5.	An error message will appear below the “Register” button that states:
a.	Connection failed: Access denied for user 'root'@'localhost' (using password: YES)

**Expected Result:**

We expect when users scrolls down to the “Join Event” section, they are able input their email and LinkedIn URL successfully.
 
•After the user fills the input and clicks “Register”, the page should remain on the footer section instead of reloading back to the top of the page
•When the data successfully is registered, a message should appear underneath the “Register” button that states: “Registration succesful!”

**Actual Result:**

Refer to the attached documents for screenshot of bug.

<img width="657" alt="bug4-registration" src="https://github.com/SeleneChoi/QA/assets/115045111/456f9379-4990-4772-8f07-5920f564dc5f">

**Comment by SeleneChoi** [comment]
To handle the issue, the script below has been added and it works properly now.

`<script>

    document.addEventListener('DOMContentLoaded', function () {
        var form = document.getElementById('registrationForm');
        var submitBtn = document.getElementById('submitBtn');
        var confirmationContainer = document.createElement('div');

        form.addEventListener('submit', function (event) {
            event.preventDefault();

            var confirmationMessage = '<div class="beige poppins col-span-full text-center font-bold italic text-xl underline underline-offset-8 decoration-orange-600">Registration successful!</div>';
            confirmationContainer.innerHTML = confirmationMessage;

            submitBtn.insertAdjacentHTML('afterend', confirmationMessage);

            setTimeout(function () {
                form.reset();
            }, 200);
        });
    });
</script>
`
