### ISSUE TITLE
Inconsistent Font-colors – Mobile & Desktop

### ISSUE THREAD

**Issue by jkc96** [SeleneChoi/QA#6]
**Description:**

When users visit different pages on the website ([www.qa-test.julie-chan.ca](http://www.qa-test.julie-chan.ca/)), there is an inconsistent styling that do not reflect the initial design mockups.

Two font colors are used in the style guide:
-	Orange is used for headings, icons, and important context to stand out
-	White is used for the body and for longer paragraphs

Ensuring a uniform format throughout every page of the website is crucial for upholding a professional visual that reinforces brand cohesion.

**Steps to Reproduce:**

This bug is found on all devices and browsers:

1.	Visit [www.qa-test.julie-chan.ca](https://qa-test.julie-chan.ca/)
2.	Visit Our Speakers page

> a.	All section headings do not display orange font-color and displays white font-color

> b.	Under Our Speakers section, there are two features speakers. The name and role are also in white font and blends with the description

3.	Visit Our Team page

> a.	All section headings do not display orange font-color and displays white font-color

> b.	LinkedIn icons located on the bottom right below team member image appear white

**Expected Result:**

We expect the following context to be the color orange.

Our Speakers Page
-	Heading 1 >> Our Speakers
-	Heading 1 >> Guest Speakers
-	Heading 3 >> Name of Speaker
-	Heading 4 >> Speaker’s Professional Role

Our Team Page
-	Heading 1 >> Meet the Team
-	Icon >> LinkedIn Icons

**Actual Result:**

Refer to the attached documents for screenshot of bug.

**Our Speaker Page**
![bug5-our-speaker](https://github.com/SeleneChoi/QA/assets/115045111/434ca5f1-bdf8-41e1-bb5e-a9b8f77edcac)

**Our Team Page**
![bug5-our-team](https://github.com/SeleneChoi/QA/assets/115045111/1dab945a-5b43-455f-a89e-4d5469a5f26c)

**Comment by SeleneChoi** [comment]
The root causation was incorrect class name.
For the orange font color, I have detected where to change to correct class name.
All font that's listed above is correctly colored now by adding correct class name.
