### ISSUE TITLE
Image Resolution – Mobile & Desktop

### ISSUE THREAD

**Issue by jkc96** [SeleneChoi/QA#8]
**Description:**

When users visit the Event Details page from (www.qa-test.julie-chan.ca/OurTeam.php), there are two images that appears pixelated. This may be a problem with the image file or issue with rendering. The low image quality impacts the overall visual experience and compromising the intended clarity of the context.

**Steps to Reproduce:**

**This bug is found on all devices and browsers:**

1.	Visit [www.qa-test.julie-chan.ca](https://qa-test.julie-chan.ca/)/
2.	Click Our Team from navigation menu
3.	Scroll down to the team members section, review following images:
a.	Hoi Wing Henry Cheung
b.	Selene Choi

**Expected Result:**

We expect when users visit the Our Teams page, the section showcases six team members. For each team member, the following is displayed 

**Desktop:**
-	Three images of members per row
-	Images take up an estimate of 30-33% of the full-page width

**Mobile**
-	Members are ordered in column
-	Each image takes up close to full width of screen, has small margin on left and right side

**Actual Result:**

Refer to the attached documents for screenshot of bug.

**Mobile**
![bug7-mobile-image-res](https://github.com/SeleneChoi/QA/assets/115045111/727d6058-855d-4789-acbd-c844145f287b)

**Desktop**
![bug7-desktop-image-res](https://github.com/SeleneChoi/QA/assets/115045111/7c19536f-88c0-43cf-b141-6f1c24d3e402)

**Comment by SeleneChoi** [comment]
The high resolution images has been updated
