### ISSUE TITLE
Missing Footer Social Icons & Copyright - Mobile & Desktop

### ISSUE THREAD

**Issue by jkc96** [SeleneChoi/QA#9]
**Description:**

When entering the url [www.qa-test.julie-chan.ca](https://qa-test.julie-chan.ca/) the footer of the website is missing three round social icons (LinkedIn, Github, Email) along with the copyright text at the bottom of the footer.

**Steps to Reproduce:**

Open on desktop, tablet, or mobile device using browsers Safari, Chrome, Firefox, or Edge.

1. )Visit [www.qa-test.julie-chan.ca](https://qa-test.julie-chan.ca/)
2.) When entering the website, the, scroll to the very bottom of the footer
a) Below the registration, there are 3 missing icons
b) Below the 3 icons there is also a missing line of text that should states "Copyright © Event 2023"

**Expected Result:**

Because the footer is a component used throughout the pages, the footer should have the following information from top to bottom:
- Heading: "Join Event"
- Body: "Register now for a future of connections and success in New Media!"
- Input: Email
- Input: LinkedIn URL (Optional)
- Button: Register
- Subheading: "Let's Connect!"
- Social Icons: LinkedIn, Github, Email
-  Copyright text: Copyright © Event 2023

**Actual Result:**

Refer to the attached documents for screenshot of bug.

**Desktop**
<img width="1437" alt="bug8-desktop-footer" src="https://github.com/SeleneChoi/QA/assets/115045111/25c6a21b-1d9e-4d5e-940b-f64d6f7d399e">

**Mobile**
![bug8-mobile-footer](https://github.com/SeleneChoi/QA/assets/115045111/9bd82d4b-238a-4ad7-aaff-46f8202a3121)

**Comment by SeleneChoi** [comment]
It's due to the conflict when two developer combined their work together. The code part has been fixed accordingly and now social icons and copyright is correctly applied by now.
